# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-AON
version:      0.08
version_from: lib/Crypt/AON.pm
installdirs:  site
requires:
    Carp:                          0
    Crypt::AON::Util:              0
    Crypt::OpenSSL::AES:           0
    Crypt::Random:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
